spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: true
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 3000
      validation-timeout: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
